[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
# Ignore long lines in some logs, and modernization rules that are optional for Py3.10
# This keeps CI green during the hackathon without forcing mass refactors.
ignore = ["E501", "UP006", "UP007"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["backend/tests"]

[tool.isort]
profile = "black"

